### ISSUE TITLE
Missing data points in data.txt 

### ISSUE THREAD

**Issue by code-Assasin** [SullyChen/driving-datasets#2]
In the dataset recorded over Rancho Palos Verdes and San Pedro California, the data.txt file is missing nearly 161 images which are present in the dataset. Are the angles correctly corresponding to the images then or are they moved up and down due to the missing files?

**Comment by SullyChen** [comment]
They should be correct, regardless of missing images. The code that synchronizes the angle measurements and img saving should not be affected by dropped images.
